<?php

namespace AppBundle\Repository;

/**
 * HangarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HangarRepository extends \Doctrine\ORM\EntityRepository
{
}
