<?php

namespace AppBundle\Repository;

/**
 * LDFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LDFRepository extends \Doctrine\ORM\EntityRepository
{
}
