<?php

namespace AppBundle\Repository;

/**
 * RestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestRepository extends \Doctrine\ORM\EntityRepository
{
}
